### ISSUE TITLE
limits on the GTS

### ISSUE THREAD

**Issue by vainesy** [imaboy321/Ledybot#30]
im having issues with the game after closing and reopening it wont reopen unless the giveaway file is deleted.

this is frustrating as it takes so long to delete the specific file names to make the custom names work for the amount of Pokemon im loading.

is there something im doing wrong or a fix for this cos it seems as though after i get to a certain number of names and close the program i cant reopen it.

im currently setting up the names of pokemon to be acting as the Pokedex value.

EG if someone wants a squirtle they name the lillipup 007 > or 150 if they want a mewtwo

after i backup my giveaway file and replace it the program still will not open.

pulling my hair out trying to sort it.

**Comment by gr33nd3v1l** [comment]
Be careful when injecting large amounts of pokemon since the bot is hardcoded up to 25 i believe. I remember having issues with large giveaways, too

**Comment by KNYuki** [comment]
This has happened to me before, though for me it wasn't due to pokemon limitations (I've had giveaways with over 300 pokemon and it's worked fine). Somehow it was due to the pokemon file itself? What I did was remove a number of recently added pokemon from the giveaway details via a text editor and that usually fixed it and to avoid the problem I import in batches so it'll be easier to go through.
