### ISSUE TITLE
Bot crashes

### ISSUE THREAD

**Issue by PumPum7** [imaboy321/Ledybot#36]
Bot always crashes the whole system on version 1.2 for me.

**Comment by Souljahx6** [comment]
Why you using version 1.2? 
The latest is 2.4.

**Comment by PumPum7** [comment]
Version 1.2 of PKMN SuMo

**Comment by Souljahx6** [comment]
Okay so theres many reasons the bot could crash. In my experience its mostly due to the wireless connection. If the bandwidth has any sudden change it delays the packets being sent and crashes the bot. 

I minimized the crashes by enabling debug mode and buying a router that only connects to the 3ds that way theres no interference, no bandwidth share and the 3ds sits right next to the router so there is no degrading signal due to walls and such.

I do giveaways for about 3 hours a at time and it crashes about 4-6 times mostly due to how fast the button press happens that ends up messing up the synchronization of ledybot and the 3ds. If i could slow down the button press it would help with stabilization.

**Comment by SteveCookTU** [comment]
NTR itself is not 100% stable over local network connections. The bot sometimes becomes out of sync with the device. This could be fixed by delaying the commands from the bot even more but it would also reduce the efficiency a lot. I will work on a fix that meets in the middle soon.
